### ISSUE TITLE
dependency issue

### ISSUE THREAD

**Issue by ali2210** [mozilla/mozilla-campus-clubs#130]
ali@Koohinoor-ceo:~/mozilla-campus-clubs$ bundle install
after few seconds 
An error occurred while installing commonmarker (0.17.13), and Bundler
cannot continue.
Make sure that `gem install commonmarker -v '0.17.13'` succeeds before
bundling.

In Gemfile:
  github-pages was resolved to 192, which depends on
    jekyll-commonmark-ghpages was resolved to 0.1.5, which depends on
      jekyll-commonmark was resolved to 1.2.0, which depends on
        commonmarker

**Comment by himankpathak** [comment]
Hi @ali2210 
commonmarker requires `ruby-dev` package to be installed on your system, try installing it before running the bundler again.

**Comment by ali2210** [comment]
Thanks                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Himank PathakSent: Tuesday, 2 October 2018 21:50To: mozilla/mozilla-campus-clubsReply To: mozilla/mozilla-campus-clubsCc: Ali Hassan; MentionSubject: Re: [mozilla/mozilla-campus-clubs] dependency issue (#130)Hi @ali2210
commonmarker requires ruby-dev package to be installed on your system, try installing it before running the bundler again.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mozilla/mozilla-campus-clubs","title":"mozilla/mozilla-campus-clubs","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/mozilla/mozilla-campus-clubs"}},"updates":{"snippets":[{"icon":"PERSON","message":"@himankpathak in #130: Hi @ali2210 \r\ncommonmarker requires `ruby-dev` package to be installed on your system, try installing it before running the bundler again."}],"action":{"name":"View Issue","url":"https://github.com/mozilla/mozilla-campus-clubs/issues/130#issuecomment-426348029"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/mozilla/mozilla-campus-clubs/issues/130#issuecomment-426348029",
"url": "https://github.com/mozilla/mozilla-campus-clubs/issues/130#issuecomment-426348029",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [mozilla/mozilla-campus-clubs] dependency issue (#130)",
"sections": [
{
"text": "",
"activityTitle": "**Himank Pathak**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@himankpathak",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"mozilla/mozilla-campus-clubs\",\n\"issueId\": 130,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"mozilla/mozilla-campus-clubs\",\n\"issueId\": 130\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/mozilla/mozilla-campus-clubs/issues/130#issuecomment-426348029"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 386997019\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by ali2210** [comment]
as you said first install ruby-dev and then install bundles
ERROR
An error occurred while installing nokogiri (1.8.4), and Bundler cannot
continue.
Make sure that `gem install nokogiri -v '1.8.4'` succeeds before bundling.

**Comment by himankpathak** [comment]
Seems like you don't have the required packages to install nokogiri, try running the following commands and see if it helps.

```
sudo apt-get install libxslt-dev libxml2-dev zlib1g-dev
sudo gem install nokogiri -v '1.8.4'
```

**Comment by ali2210** [comment]
thanks it work
