### ISSUE TITLE
White margin for resolutions < 900

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/mozilla-campus-clubs#21]
1. Use Responsive Design Mode from Developers tool and go to https://campus.mozilla.community/get-started/
2. Set resolutions less than 900 ( first parameter) - aka phones, tablets etc 
3. Check footer and header 

![screen shot 2016-10-17 at 16 49 00](https://cloud.githubusercontent.com/assets/1391451/19440241/dd14a346-9489-11e6-9f1c-d31de13f130a.png)

<img src="https://cloud.githubusercontent.com/assets/1391451/19440722/9a114034-948b-11e6-8562-02a96e3bbe86.jpg" width="300" height="550" /> 

<img src="https://cloud.githubusercontent.com/assets/1391451/19440721/99f741a2-948b-11e6-8c90-ca4921763421.jpg" width="300" height="550" />

**Comment by razat249** [comment]
Hello @ioana-chiorean. I have created a PR solving this issue and #22. Here are some screenshots


**Mobile view (screen < 900px)**
![image](https://cloud.githubusercontent.com/assets/10090911/24770294/0e871b06-1b27-11e7-8ad8-250e2ec375f6.png)

**Desktop view (screen > 900px)**
![image](https://cloud.githubusercontent.com/assets/10090911/24770183/b1c9a5dc-1b26-11e7-8081-8c7df1fbfb88.png)
