### ISSUE TITLE
Outdated Campus Clubs registration form

### ISSUE THREAD

**Issue by kindavishal** [mozilla/mozilla-campus-clubs#217]
The Campus Clubs registration form is closed but also shows a date of 26th September 2016 which is very misleading for the new Campus Club Captains!
Form link: https://docs.google.com/forms/d/e/1FAIpQLSfBlMnvOVn6xUMrvBgYWJaEg4npDLUFkhbusLorfZ4BqSJgJQ/closedform

**Comment by bacharakis** [comment]
Hi Vishal, may I ask where did you find this form?

This is not a public or a form linked to our website. This is a form from
2016.

Cheers
-Christos

**Comment by kindavishal** [comment]
Hi Bacharakis,
Try the first link which says "Apply to start a Mozilla Campus Club" here: https://campus.mozilla.community/resources/

**Comment by bacharakis** [comment]
Thanks @VishalDas95 
everything is update now. Cheers
