### ISSUE TITLE
Add previews of the posters to the resource page 

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/mozilla-campus-clubs#30]
Can we add small images to the resource section that show people the posters they can download? 
https://campus.mozilla.community/resources/

**Comment by LucyeoH-zz** [comment]
@comzeradd I tried and failed at this a few weeks ago. I don't know how to do this. Can you make small clickable images appear underneath this section like this:

![campus website poster mock-up](https://cloud.githubusercontent.com/assets/8070833/20498512/73ed2dec-affb-11e6-8a44-9ec82831c4cc.png)


All the poster files are [here](https://drive.google.com/drive/folders/0B3DoAOpplvFcNFA5eUVIOVhkMlk). 

cc: @bacharakis

**Comment by comzeradd** [comment]
I'd prefer we don't suggest/promote proprietary formats or tools. PDF files are vector and can be edited by both Illustrator and Open Source tools (eg. Inkscape). If we think PDFs are not enough, it would be better to add SVG files, which is the standard for vector graphics.

**Comment by LucyeoH-zz** [comment]
@comzeradd Feel free to put them up in whatever file type you'd prefer. My goal is to have one that's easy to edit partially (to fill in the fields), and another format that allows for complete editing.
