### ISSUE TITLE
Track outbound links 

### ISSUE THREAD

**Issue by bacharakis** [mozilla/mozilla-campus-clubs#31]
Hey we are currently not tracking outbound links clicks.
https://support.google.com/analytics/answer/1136920?hl=en

Can you add this functionality please?

**Comment by hmitsch** [comment]
@comzeradd, can you have a look at this? If it is doable as "unplanned" let's tag it accordingly. I added a Taiga card to the board and put it into the "red zone":

https://tree.taiga.io/project/pierros-mozilla-particiaption-systems/us/230?kanban-status=904519

**Comment by comzeradd** [comment]
Do we use Google's Tag Manager for our Analytics? I'd avoid a `onclick` code on each link on the website.

**Comment by hmitsch** [comment]
@comzeradd, no we do NOT use GTM (Google Tag Manager). If GTM works fine with the site, I am more than happy to create a GTM account.

**Comment by comzeradd** [comment]
Outbound Links tracking seems to work now.

**Comment by hmitsch** [comment]
Example screenshot from Google Analytics

![image](https://cloud.githubusercontent.com/assets/869692/20390360/cf8cea14-acce-11e6-8e31-231c1e5c0740.png)
