### ISSUE TITLE
Update Homepage Template & Content

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/mozilla-campus-clubs#35]
Please update the layout and content of the Campus homepage with the following information:

Content - [link](https://docs.google.com/document/d/1e7HnMGpG5809yH8us3650mqfCnNiTjwC9y4mN4n1y2g/edit#)

Wireframe - [link](https://drive.google.com/open?id=0Bwl5PnEA3iBfR09IWmsxNGtBbHNla0owNjhHbXgwSjROYXEw)

NOTE: Where the content and the wireframe digress please use the layout in the content document. The discrepancies are: 
* We want to keep the "Start a Club" button at the top of the page
* We do not want the "view resources" and "view activities" button after the Mission description
* We want to add a link to the activities page beneath the activity description

Please let me know if you have any questions!
cc: @bacharakis

**Comment by LucyeoH-zz** [comment]
@comzeradd can we aim to have this new version live by Thursday Nov 24th?

**Comment by comzeradd** [comment]
I can probably have a Pull Request by tomorrow. Worst case it goes live on Friday.
