### ISSUE TITLE
Re-Arrange Activities & Re-Name Tabs 

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/mozilla-campus-clubs#37]
Build Tab - Fine as is

"Teach"  Tab renamed to  "Learn" Tab - HTML 5 game activity, GitHub Intro, Tor on Campus (Learn about Tor), Learn about Tracking, Cyber Security & Government Surveillance. 

Protect Tab -> Rename as "Advocate"

**Comment by comzeradd** [comment]
Can you list the activities each Tab should have? Just to make sure we don't mix anything. I see you list some activities under the "Learn" Tab that currently are under "Protect".

**Comment by LucyeoH-zz** [comment]
@bacharakis did this!
