### ISSUE TITLE
Incorret redirect on homepage

### ISSUE THREAD

**Issue by felipez3r0** [mozilla/mozilla-campus-clubs#52]
When I click in the link **"Find out how your club can start building open source VR on the web ->"** I am redirected to: https://mozilla.github.io/mozilla-campus-clubs/activities/#vr-activity and this broke the website visualization.

**Comment by comzeradd** [comment]
Thanks for reporting. Fixed at c528671e9a65bf4cc97266ee8b95af9de71acc91.
