### ISSUE TITLE
Footer logo don't appear

### ISSUE THREAD

**Issue by ftonato** [mozilla/mozilla-campus-clubs#69]
hey everyone =)

In the file [app.css on line 403](https://github.com/mozilla/mozilla-campus-clubs/blob/afe5a7d3015d1504c6c38b50206a1b450b6d0973/static/css/app.css#L403).
We're using a file that [does not exist](https://www.mozilla.org/media/img/sandstone/footer-mozilla.png).

**Comment by vipinkhushu** [comment]
Can i fix this? Please provide me with the graphic which is meant to be put.

**Comment by ftonato** [comment]
Yeah, you can fix!
I think this is the correct graphic: [MOZ-footer_logo](https://www.mozilla.org/media/img/pebbles/moz-wordmark-dark-reverse.2cbc28bb9895.svg)

**Comment by vipinkhushu** [comment]
Please merge https://github.com/mozilla/mozilla-campus-clubs/pull/72 for the fix to this issue
