### ISSUE TITLE
Please update the following details.

### ISSUE THREAD

**Issue by rishabh-bansal** [mozilla/mozilla-campus-clubs#85]
https://campus.mozilla.community/connect/

Northern India Engineering College has now two club captains:

- Rishabh Bansal https://mozillians.org/en-US/u/rishabhbansal/
- Shivam Singhal https://mozillians.org/en-US/u/Shivams2799/

![screen shot 2017-12-10 at 7 07 58 pm](https://user-images.githubusercontent.com/25722258/33805357-80732650-dddd-11e7-8882-956042ab2f08.png)

**Comment by rishabh-bansal** [comment]
@bacharakis Please have a look at it.

**Comment by bacharakis** [comment]
Hi @rishabh-bansal and thanks for the heads up. Apologies for the late reply, I just saw this because we are using zenhub and this issue fall outside our board.

I'll look into this and get back to you ASAP.
Cheers
-Christos
