### ISSUE TITLE
Updating the FAQ

### ISSUE THREAD

**Issue by fayepal** [mozilla/mozilla-campus-clubs#86]
Updating the FAQ in line with the changes on the program

- [x] Update the FAQ with the changes in the application period
- [x] Make the FAQ available on the website instead of Discourse

**Comment by yatri1609** [comment]
@fayepal I would like to work on this issue? Can you pass me the details which need to be changed?

**Comment by bacharakis** [comment]
Hi @yatri1609, we have updated the FAQ page but thanks for your offer!

**Comment by bacharakis** [comment]
Hi @yatri1609, we have updated the FAQ page but thanks for your offer!
